<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="11" passed="7" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-11-12T11:52:09 IST" name="Default suite" finished-at="2020-11-12T12:07:29 IST" duration-ms="919851">
    <groups>
    </groups>
    <test started-at="2020-11-12T11:52:09 IST" name="Default test" finished-at="2020-11-12T12:07:29 IST" duration-ms="919851">
      <class name="AEC_Testcase.AEC_testcase_search">
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:52:09 IST" name="setup" finished-at="2020-11-12T11:52:53 IST" duration-ms="43978" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="intake_filter()[pri:1, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:52:53 IST" name="intake_filter" finished-at="2020-11-12T11:54:52 IST" duration-ms="118600" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intake_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:54:52 IST" name="setup" finished-at="2020-11-12T11:55:25 IST" duration-ms="32542" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="delivery_method_filter()[pri:2, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:55:25 IST" name="delivery_method_filter" finished-at="2020-11-12T11:56:07 IST" duration-ms="42838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delivery_method_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:56:07 IST" name="setup" finished-at="2020-11-12T11:56:40 IST" duration-ms="32407" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="current_status_filter()[pri:3, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:56:40 IST" name="current_status_filter" finished-at="2020-11-12T11:57:11 IST" duration-ms="30846" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- current_status_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:57:11 IST" name="setup" finished-at="2020-11-12T11:57:53 IST" duration-ms="42656" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="course_level_filter()[pri:4, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:57:53 IST" name="course_level_filter" finished-at="2020-11-12T11:59:10 IST" duration-ms="76795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- course_level_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:59:10 IST" name="setup" finished-at="2020-11-12T11:59:42 IST" duration-ms="31885" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="application_requirement_filter()[pri:5, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T11:59:42 IST" name="application_requirement_filter" finished-at="2020-11-12T12:00:41 IST" duration-ms="59114" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- application_requirement_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:00:41 IST" name="setup" finished-at="2020-11-12T12:01:16 IST" duration-ms="34568" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="tution_fee_filter()[pri:6, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:01:16 IST" name="tution_fee_filter" finished-at="2020-11-12T12:01:21 IST" duration-ms="5715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tution_fee_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:01:21 IST" name="setup" finished-at="2020-11-12T12:01:59 IST" duration-ms="37437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="duration_filter()[pri:7, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:01:59 IST" name="duration_filter" finished-at="2020-11-12T12:02:05 IST" duration-ms="5747" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Courses (1) available in (1) Institutes] but found [Courses (8) available in (4) Institutes]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Courses (1) available in (1) Institutes] but found [Courses (8) available in (4) Institutes]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at AEC_Testcase.AEC_testcase_search.duration_filter(AEC_testcase_search.java:162)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- duration_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:02:05 IST" name="setup" finished-at="2020-11-12T12:02:44 IST" duration-ms="38787" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="internship_period_filter()[pri:8, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:02:44 IST" name="internship_period_filter" finished-at="2020-11-12T12:02:49 IST" duration-ms="5707" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Courses (1) available in (1) Institutes] but found [Courses (11) available in (5) Institutes]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Courses (1) available in (1) Institutes] but found [Courses (11) available in (5) Institutes]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at AEC_Testcase.AEC_testcase_search.internship_period_filter(AEC_testcase_search.java:170)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- internship_period_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:02:49 IST" name="setup" finished-at="2020-11-12T12:03:32 IST" duration-ms="42785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="application_fee_filter()[pri:9, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:03:32 IST" name="application_fee_filter" finished-at="2020-11-12T12:03:38 IST" duration-ms="5783" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Courses (1) available in (1) Institutes] but found [Courses (11) available in (5) Institutes]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Courses (1) available in (1) Institutes] but found [Courses (11) available in (5) Institutes]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at AEC_Testcase.AEC_testcase_search.application_fee_filter(AEC_testcase_search.java:178)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- application_fee_filter -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:03:38 IST" name="setup" finished-at="2020-11-12T12:04:28 IST" duration-ms="50040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="allfilter1()[pri:10, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:04:28 IST" name="allfilter1" finished-at="2020-11-12T12:06:31 IST" duration-ms="123572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allfilter1 -->
        <test-method is-config="true" signature="setup()[pri:0, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:06:31 IST" name="setup" finished-at="2020-11-12T12:07:07 IST" duration-ms="35648" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="allfilter2()[pri:11, instance:AEC_Testcase.AEC_testcase_search@672872e1]" started-at="2020-11-12T12:07:07 IST" name="allfilter2" finished-at="2020-11-12T12:07:28 IST" duration-ms="20940" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Courses (1) available in (1) Institutes] but found [Courses (9) available in (4) Institutes]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Courses (1) available in (1) Institutes] but found [Courses (9) available in (4) Institutes]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at AEC_Testcase.AEC_testcase_search.allfilter2(AEC_testcase_search.java:260)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allfilter2 -->
      </class> <!-- AEC_Testcase.AEC_testcase_search -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
